### ISSUE TITLE
Question about increase_loss parameter in sst task

### ISSUE THREAD

**Issue by svetlana21** [Eric-Wallace/universal-triggers#10]
Hello
I have a small question about sst task code. Should the `increase_loss` parameter be set to `False` when `dataset_label_filter = "1"`?

**Comment by Eric-Wallace** [comment]
Since SST is binary, its sufficient to keep the increase_loss to True. If you want to make a positive/negative trigger use dataset filter 0/1. Hope this helps.

**Comment by svetlana21** [comment]
Ok, thanks
