### ISSUE TITLE
Generating a common trigger for all classes

### ISSUE THREAD

**Issue by NoviScl** [Eric-Wallace/universal-triggers#12]
Hi Eric,

I notice that you generated triggers separately for each class (e.g., generate a trigger for positive examples, and generate another one for negative examples). Have you tried generating a common trigger for all different classes (just set the target label to a different label than the original label)?  Any chance it could work well?

**Comment by Eric-Wallace** [comment]
Hello,

I tried this for classification with little success. The trigger has to simultaneously push positive examples to negative, and negative to positive, which seems hard.

One thing I did which was more successful was to do this for SQuAD. I don't remember the numbers, but before I did the targeted attack where I try to get the model to output a particular phrase in the concatenated sentence, I just tried to make the model's confidence in the correct answer go down. I think what ended up happening is that the model usually ended up picking a phrase inside the concatenated sentence anyway, so then I just moved to directly optimizing for this with the targeted version instead.
