### ISSUE TITLE
hotflip attack implementation

### ISSUE THREAD

**Issue by mehdimashayekhi** [Eric-Wallace/universal-triggers#2]
Hi Thanks for sharing the code. I have a quick question about the implementation of hotflip_attack (equation 2 of paper) (https://github.com/Eric-Wallace/universal-triggers/blob/2e4bc9363ca547105ebdd9a09f37f6898a03f46a/attacks.py#L8) in the equation embedding of vocabulary is subtracted from embedding of adversary (e_i-e_adv), but I don't see this in the implementation, I really appreciate your response!

**Comment by Eric-Wallace** [comment]
Hi. Since we want to minimize e_i, and since the e_adv is not dependent on e_i, we can just drop that from the equation.

So I am just doing e_i * grad, rather than [e_i - e_adv] * grad.

If you add the subtraction term, the final candidates should be the exact same.

**Comment by mehdimashayekhi** [comment]
Ahh, totally, thanks much for your reply!
