### ISSUE TITLE
How are “target_texts” generated?

### ISSUE THREAD

**Issue by zhaishengfang** [Eric-Wallace/universal-triggers#24]
Thank you for your wonderful work! 
I'd like to ask How are “target_texts” generated, in "Conditional Text Generation" ?
Is there a strategy in this step?

**Comment by Eric-Wallace** [comment]
Target texts were taken from a set of offensive tweets that I had scraped from twitter myself. I probably won’t mention more details of how to get those because they are very toxic and racist. In general, you should be able to set the target texts to be whatever you want.

**Comment by zhaishengfang** [comment]
Thank you for your rely !
