### ISSUE TITLE
Sentiment word filtering for sst attack

### ISSUE THREAD

**Issue by Danielpark1239** [Eric-Wallace/universal-triggers#25]
Hi Eric, I'm looking at your paper for a school project and was wondering if you had the code to filter positive/negative sentiment words for the triggers generated during the sst attack. Any help would be appreciated!

**Comment by Eric-Wallace** [comment]
Hey I don't have this code available anymore. It should be somewhat straightforward to implement it. You can grab a sentiment dictionary, and then just filter through the candidate words returned by the attack and delete those that are in the dictionary.

**Comment by Danielpark1239** [comment]
Thanks for the quick response on an old repo! I'll try doing that.
