### ISSUE TITLE
getting best candidates (beam search)

### ISSUE THREAD

**Issue by mehdimashayekhi** [Eric-Wallace/universal-triggers#3]
Apologies for multiple questions, in this function (https://github.com/Eric-Wallace/universal-triggers/blob/2e4bc9363ca547105ebdd9a09f37f6898a03f46a/utils.py#L119)
maybe I am missing something but shouldn't this line (https://github.com/Eric-Wallace/universal-triggers/blob/2e4bc9363ca547105ebdd9a09f37f6898a03f46a/utils.py#L138) go inside the first for loop? thanks

**Comment by Eric-Wallace** [comment]
O jeez, you are right, good catch. This is a regression from refactoring the code, based on looking at the old (private) version.

I am not actually sure how/if this will affect the performance of the final trigger.

The current version you linked will basically try the candidate tokens at all positions from left to right. Then, the returned trigger sequence will have a single token replaced in the best position.

If you instead move line 138 into the first for loop, this will do left-to-right beam search, i.e., it will replace multiple tokens in the new trigger sequence.

**Comment by Eric-Wallace** [comment]
Given that generating triggers is more of an art than a science at this point, I would actually recommend trying the search with/without this line tabbed in, and see which provides better results.

For now, I think I will tab in line 138 on the master code, does that seem reasonable?

**Comment by mehdimashayekhi** [comment]
thanks much for your reply. Ok,  I am not really an expert, but I would think not doing a beam search, and the way you originally did it might be suboptimal,

**Comment by Eric-Wallace** [comment]
fixed in latest commit.
