### ISSUE TITLE
how to slove the question?thank you 

### ISSUE THREAD

**Issue by Frank-LXR** [Eric-Wallace/universal-triggers#4]
when I run "python sst.py",this error always exist.So,please tell me how to slove this error.
    
error:
   " from pytorch_transformers.tokenization_auto import AutoTokenizer
ModuleNotFoundError: No module named 'pytorch_transformers.tokenization_auto'   "

thank  you   @Eric-Wallace

**Comment by Eric-Wallace** [comment]
Hi, which version of pytorch transformers are you using? If you follow the instructions in the readme, you should have a specific version of pytorch transformers that has this module.

**Comment by Eric-Wallace** [comment]
Hi, which version of pytorch transformers are you using? If you follow the instructions in the readme, you should have a specific version of pytorch transformers that has this module.

**Comment by Frank-LXR** [comment]
> Hi, which version of pytorch transformers are you using? If you follow the instructions in the readme, you should have a specific version of pytorch transformers that has this module.

Hi，I check the requirements.txt
torch =1.1.0
numpy =1.16.3
pyorch_transforms==1.0.0
allennlp ==0.8.5
scikit_learn==0.21.3

according to Readme,
when I run the code"pip install -r requirements.txt". it has this error:

"collectin pyorch_transforms==1.0.0(from..)  "
"cache entry deserialization failed,entry ignored"

so I try to slove it.but not. 

thank you! @Eric-Wallace

**Comment by Eric-Wallace** [comment]
Hi, you should investigate why pip is not installing the version you need. Are you creating a new anaconda environment as the readme says?

Alternatively, try to remove your pip cache at by ‘ rm -rf ~/.cache/pip’ or use ‘—no-cache-dir’ when doing the pip install.

**Comment by echodarkstar** [comment]
AllenNLP has a dependency of pytorch-transformers==1.1.0, as opposed to the 1.0.0 in the requirements.txt file. I'm running the code successfully using this version.

**Comment by Eric-Wallace** [comment]
Yeah, I think it should work with pytorch transformers versions >= 1.0.

I am going to close this issue, try to make sure your environment is set up with the proper dependencies.
