### ISSUE TITLE
Comparing model accuracies for SNLI

### ISSUE THREAD

**Issue by daysm** [Eric-Wallace/universal-triggers#7]
When comparing the accuracy of `esim-glove-snli` with `decomposable-attention`, it seems like the the accuracy computed for the second model is not computed correctly.

Am I missing something here?

Here's a [Colab](https://colab.research.google.com/drive/1knrYgqoFMyrv4eO5NmRHwrJChGw422LN).

```python
# Load model and vocab
model = load_archive('https://allennlp.s3-us-west-2.amazonaws.com/models/esim-glove-snli- 
2019.04.23.tar.gz').model
model.eval().cuda()
vocab = model.vocab

# Get original accuracy before adding universal triggers
utils.get_accuracy(model, subset_dev_dataset, vocab, trigger_token_ids=None, snli=True)
```
```bash
100%|██████████| 53676932/53676932 [00:00<00:00, 62451888.15B/s]
Without Triggers: 0.9095824571943527
```

````python
# Load model and vocab
model2 = load_archive('https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable-attention-2017.09.04.tar.gz').model
model2.eval().cuda()
vocab2 = model2.vocab

# Get original accuracy before adding universal triggers
utils.get_accuracy(model2, subset_dev_dataset, vocab2, trigger_token_ids=None, snli=True)
````

````bash
100%|██████████| 38907176/38907176 [00:00<00:00, 77210263.22B/s]
Did not use initialization regex that was passed: .*token_embedder_tokens\\\\._projection.*weight
Without Triggers: 0.42805647341544006
````

**Comment by Eric-Wallace** [comment]
Hi, sorry for the delay. I was on vacation for the holidays.

I think what happens is when you load a second model, it does not use the correct vocabulary object. if you run the code in the opposite order (i.e., first load the decomposable attention), it will work correctly, but the esim model won't work. Let me see if this in on my end, or whether this is an allennlp problem.

**Comment by Eric-Wallace** [comment]
Ok, I have a simple fix. I just added a bunch of deepcopy() around everything to be safe. Its probably overkill but it seems to fix it. https://colab.research.google.com/drive/1knrYgqoFMyrv4eO5NmRHwrJChGw422LN

**Comment by Eric-Wallace** [comment]
Going to close the issue, feel free to reopen if it is not fully resolved.
